### ISSUE TITLE
Allow concurrent builds 

### ISSUE THREAD

**Issue by ottlinger** [mojohaus/versions-maven-plugin#293]
Thanks for the great plugin!

When I integrated it into our builds as follows:
`$ versions:display-dependency-updates versions:plugin-updates-report enforcer:display-info -U -B -T8`
I get the warning:
`21:28:50 [INFO] --------------------------------[ pom ]---------------------------------
21:28:50 [WARNING] *****************************************************************
21:28:50 [WARNING] * Your build is requesting parallel execution, but project      *
21:28:50 [WARNING] * contains the following plugin(s) that have goals not marked   *
21:28:50 [WARNING] * as @threadSafe to support parallel building.                  *
21:28:50 [WARNING] * While this /may/ work fine, please look for plugin updates    *
21:28:50 [WARNING] * and/or request plugins be made thread-safe.                   *
21:28:50 [WARNING] * If reporting an issue, report it against the plugin in        *
21:28:50 [WARNING] * question, not against maven-core                              *
21:28:50 [WARNING] *****************************************************************
21:28:50 [WARNING] The following plugins are not marked @threadSafe in 365 FarmNet Monolith Builder:
21:28:50 [WARNING] org.codehaus.mojo:versions-maven-plugin:2.5
21:28:50 [WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
21:28:50 [WARNING] *****************************************************************
21:28:50 [INFO] `

Can the plugin be made threadSafe by adding the annotation or are there things in the code that are not concurrently executable?

Thanks

**Comment by dannil** [comment]
This was fixed with #219, my installed version of 2.6-SNAPSHOT with Maven 3.5.2 doesn't output the warning.

**Comment by khmarbaise** [comment]
@dannil Thanks reporting this.

**Comment by renedewaele** [comment]
I'm still getting this warning using Maven 3.5.4 and version 2.7 of the plugin. See:

```*****************************************************************
* Your build is requesting parallel execution, but project      *
* contains the following plugin(s) that have goals not marked   *
* as @threadSafe to support parallel building.                  *
* While this /may/ work fine, please look for plugin updates    *
* and/or request plugins be made thread-safe.                   *
* If reporting an issue, report it against the plugin in        *
* question, not against maven-core                              *
*****************************************************************
The following plugins are not marked @threadSafe in Flux Capacitor:
org.codehaus.mojo:versions-maven-plugin:2.7
Enable debug to see more precisely which goals are not marked @threadSafe.
*****************************************************************

**Comment by khmarbaise** [comment]
Please don't reuse old issue better create a new one.. Also helpful would be how you called the versions plugin and also which version of the plugin you are using ?
